#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

# Get PIDs of Gunicorn master processes
PIDS=$(ps aux | grep gunicorn | awk '{ print $2 }')

# Check if there are any PIDs
if [ -z "$PIDS" ]; then
  echo "No Gunicorn processes found."
  exit 1
fi

# Send HUP signal to all Gunicorn master processes
echo "$PIDS" | xargs kill -HUP

# Verify success
if [ $? -eq 0 ]; then
  echo "Gunicorn processes reloaded gracefully."
else
  echo "Failed to reload Gunicorn processes."
  exit 1
fi
